import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createTestDatabase, createTenantWithOwner, createUser, type TestDb } from './db/setup';

/**
 * Replaces gift-redemption.test.ts — see docs/DECISIONS.md "Referral
 * program replaces gifting". Every tenant gets a referral_code on
 * creation (generated by a trigger); record_referral links a new
 * tenant to whoever's code they signed up with; reward_referral (called
 * from the Stripe webhook, service_role only) credits the referrer's
 * quota with the invitee's plan allowance exactly once, the first time
 * the invitee's subscription checkout completes.
 */
describe('referral program (invite -> free stories)', () => {
  let db: TestDb;
  let referrerOwnerId: string;
  let referrerTenantId: string;
  let referrerCode: string;
  let familyPlanId: string;

  beforeAll(async () => {
    db = await createTestDatabase();
    referrerOwnerId = await createUser(db.adminClient, 'Referrer');
    referrerTenantId = await createTenantWithOwner(db.adminClient, referrerOwnerId, 'Referrer Family');

    const codeRow = await db.adminClient.query('select referral_code from tenants where id = $1', [
      referrerTenantId,
    ]);
    referrerCode = codeRow.rows[0].referral_code;

    const plan = await db.adminClient.query(
      `insert into plans (key, name, price_monthly_cents, price_annual_cents, stories_per_month, audience)
       values ('family', 'Family', 900, 9700, 3, 'family')
       returning id`,
    );
    familyPlanId = plan.rows[0].id;
  }, 60_000);

  afterAll(async () => db.teardown());

  async function createInvitee(label: string): Promise<{ ownerId: string; tenantId: string }> {
    const ownerId = await createUser(db.adminClient, label);
    const tenantId = await createTenantWithOwner(db.adminClient, ownerId, `${label} Family`);
    return { ownerId, tenantId };
  }

  it('every tenant gets a unique referral_code automatically on creation', async () => {
    expect(referrerCode).toMatch(/^[A-Z0-9]{8}$/);
  });

  it('record_referral links a new tenant to the referrer for a valid code', async () => {
    const invitee = await createInvitee('Invitee One');

    const client = await db.connectAs({ role: 'authenticated', userId: invitee.ownerId });
    await client.query('select record_referral($1, $2)', [referrerCode, invitee.tenantId]);
    await client.end();

    const { rows } = await db.adminClient.query(
      'select referrer_tenant_id, status, reward_stories from referrals where invitee_tenant_id = $1',
      [invitee.tenantId],
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].referrer_tenant_id).toBe(referrerTenantId);
    expect(rows[0].status).toBe('pending');
    expect(rows[0].reward_stories).toBeNull();
  });

  it('is a silent no-op for an unknown code', async () => {
    const invitee = await createInvitee('Invitee Two');

    const client = await db.connectAs({ role: 'authenticated', userId: invitee.ownerId });
    await client.query('select record_referral($1, $2)', ['NOPE1234', invitee.tenantId]);
    await client.end();

    const { rows } = await db.adminClient.query(
      'select count(*)::int as count from referrals where invitee_tenant_id = $1',
      [invitee.tenantId],
    );
    expect(rows[0].count).toBe(0);
  });

  it('is a silent no-op for a self-referral', async () => {
    const client = await db.connectAs({ role: 'authenticated', userId: referrerOwnerId });
    await client.query('select record_referral($1, $2)', [referrerCode, referrerTenantId]);
    await client.end();

    const { rows } = await db.adminClient.query(
      'select count(*)::int as count from referrals where invitee_tenant_id = $1',
      [referrerTenantId],
    );
    expect(rows[0].count).toBe(0);
  });

  it('is a silent no-op for an empty code (no referral, no error)', async () => {
    const invitee = await createInvitee('Invitee Empty Code');

    const client = await db.connectAs({ role: 'authenticated', userId: invitee.ownerId });
    await client.query("select record_referral('', $1)", [invitee.tenantId]);
    await client.end();

    const { rows } = await db.adminClient.query(
      'select count(*)::int as count from referrals where invitee_tenant_id = $1',
      [invitee.tenantId],
    );
    expect(rows[0].count).toBe(0);
  });

  it("reward_referral credits the referrer with the invitee's plan allowance, exactly once", async () => {
    const invitee = await createInvitee('Invitee Three');

    const inviteeClient = await db.connectAs({ role: 'authenticated', userId: invitee.ownerId });
    await inviteeClient.query('select record_referral($1, $2)', [referrerCode, invitee.tenantId]);
    await inviteeClient.end();

    const before = await db.adminClient.query(
      'select coalesce(stories_included_this_period, 0) as included from quotas where tenant_id = $1',
      [referrerTenantId],
    );
    const includedBefore = before.rows[0]?.included ?? 0;

    const service = await db.connectAs({ role: 'service_role' });
    await service.query('select reward_referral($1, $2)', [invitee.tenantId, familyPlanId]);
    // A second call (e.g. the invitee later upgrades and checks out again)
    // must not credit the referrer a second time — status is already
    // 'rewarded' by this point.
    await service.query('select reward_referral($1, $2)', [invitee.tenantId, familyPlanId]);
    await service.end();

    const after = await db.adminClient.query(
      'select stories_included_this_period from quotas where tenant_id = $1',
      [referrerTenantId],
    );
    expect(after.rows[0].stories_included_this_period - includedBefore).toBe(3); // familyPlanId's stories_per_month

    const referral = await db.adminClient.query(
      'select status, reward_stories from referrals where invitee_tenant_id = $1',
      [invitee.tenantId],
    );
    expect(referral.rows[0].status).toBe('rewarded');
    expect(referral.rows[0].reward_stories).toBe(3);
  });

  it('is a no-op if the invitee was never referred', async () => {
    const invitee = await createInvitee('Invitee Never Referred');

    const service = await db.connectAs({ role: 'service_role' });
    await expect(
      service.query('select reward_referral($1, $2)', [invitee.tenantId, familyPlanId]),
    ).resolves.toBeTruthy();
    await service.end();

    const { rows } = await db.adminClient.query(
      'select count(*)::int as count from referrals where invitee_tenant_id = $1',
      [invitee.tenantId],
    );
    expect(rows[0].count).toBe(0);
  });

  it('a tenant cannot call reward_referral themselves — only service_role may', async () => {
    const invitee = await createInvitee('Invitee Four');
    const client = await db.connectAs({ role: 'authenticated', userId: invitee.ownerId });
    await expect(
      client.query('select reward_referral($1, $2)', [invitee.tenantId, familyPlanId]),
    ).rejects.toThrow(/permission denied/i);
    await client.end();
  });

  it('a referrer can read their own referrals, but not another tenant\'s', async () => {
    const outsiderId = await createUser(db.adminClient, 'Outsider');

    const referrerClient = await db.connectAs({ role: 'authenticated', userId: referrerOwnerId });
    const own = await referrerClient.query('select count(*)::int as count from referrals where referrer_tenant_id = $1', [
      referrerTenantId,
    ]);
    expect(own.rows[0].count).toBeGreaterThan(0);
    await referrerClient.end();

    const outsiderClient = await db.connectAs({ role: 'authenticated', userId: outsiderId });
    const outsiderView = await outsiderClient.query(
      'select count(*)::int as count from referrals where referrer_tenant_id = $1',
      [referrerTenantId],
    );
    expect(outsiderView.rows[0].count).toBe(0);
    await outsiderClient.end();
  });

  it('get_referral_summary reports the tenant\'s own code and running totals', async () => {
    const client = await db.connectAs({ role: 'authenticated', userId: referrerOwnerId });
    const { rows } = await client.query('select (get_referral_summary($1)).*', [referrerTenantId]);
    await client.end();

    expect(rows[0].referral_code).toBe(referrerCode);
    expect(rows[0].rewarded_count).toBeGreaterThanOrEqual(1);
    expect(rows[0].total_stories_earned).toBeGreaterThanOrEqual(3);
  });

  it('get_referral_summary refuses a caller who is not a member of that tenant', async () => {
    const outsiderId = await createUser(db.adminClient, 'Outsider Two');
    const client = await db.connectAs({ role: 'authenticated', userId: outsiderId });
    await expect(client.query('select (get_referral_summary($1)).*', [referrerTenantId])).rejects.toThrow(
      /not authorized/i,
    );
    await client.end();
  });

  it('no client role can write directly to referrals — only the SECURITY DEFINER RPCs can', async () => {
    const invitee = await createInvitee('Invitee Direct Write');
    const client = await db.connectAs({ role: 'authenticated', userId: invitee.ownerId });
    await expect(
      client.query('insert into referrals (referrer_tenant_id, invitee_tenant_id) values ($1, $2)', [
        referrerTenantId,
        invitee.tenantId,
      ]),
    ).rejects.toThrow(/row-level security|permission denied/i);
    await client.end();
  });
});
