import type { GenerateImageRequest, GenerateImageResult, ImageProvider } from './ImageProvider';
import { ImageGenerationError } from './ImageProvider';

/**
 * Deterministic, free, zero-latency image "generation" used in dev, tests,
 * and CI, and as the default in production until FEATURE_REAL_IMAGE_PROVIDER
 * is explicitly turned on. Produces a simple SVG placeholder that encodes
 * the avatar's outfit colour and the prompt text, so approval-flow UI has
 * something real to render per page without any external dependency or
 * cost.
 */
export class MockImageProvider implements ImageProvider {
  readonly name = 'mock';

  /** Set via constructor in tests to exercise retry logic deterministically. */
  constructor(private readonly failNextAttempts = 0) {}

  private attemptCounts = new Map<string, number>();

  async generate(request: GenerateImageRequest): Promise<GenerateImageResult> {
    const attempts = (this.attemptCounts.get(request.pageId) ?? 0) + 1;
    this.attemptCounts.set(request.pageId, attempts);

    if (attempts <= this.failNextAttempts) {
      throw new ImageGenerationError('Mock provider simulated failure', true);
    }

    const outfitColor = request.avatarConfig.outfitColor ?? '#20949c';
    const svg = renderPlaceholderSvg(request.prompt, outfitColor);

    return {
      bytes: new TextEncoder().encode(svg),
      contentType: 'image/svg+xml',
      provider: this.name,
      costUsd: 0,
    };
  }
}

export function renderPlaceholderSvg(prompt: string, outfitColor: string): string {
  const safePrompt = escapeXml(prompt).slice(0, 180);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000">
  <rect width="1000" height="1000" fill="#FFF8EC" />
  <circle cx="500" cy="380" r="220" fill="${outfitColor}" opacity="0.25" />
  <circle cx="500" cy="330" r="120" fill="#F7A020" />
  <rect x="380" y="440" width="240" height="260" rx="60" fill="${outfitColor}" />
  <text x="60" y="900" font-family="sans-serif" font-size="28" fill="#3C3025">${safePrompt}</text>
  <text x="60" y="950" font-family="sans-serif" font-size="20" fill="#8A7454">Mock illustration — not generated by AI</text>
</svg>`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
