import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface SampleStoryPage {
  pageNumber: number;
  text: string;
  publicPath: string;
}

export type SampleStoryManifest = Partial<Record<'en' | 'ar', SampleStoryPage[]>>;

const MANIFEST_PATH = join(process.cwd(), 'public', 'images', 'marketing', 'sample-stories', 'manifest.json');

/**
 * The real, four-page English and Arabic sample stories generated by
 * `npm run generate-sample-stories` (see docs/DECISIONS.md "Real sample
 * stories generated for the landing/home page carousel") — static files
 * under public/, not signed Storage URLs, so they work on a page that
 * may be statically rendered or CDN-cached (a 10-minute signed URL
 * baked into that HTML would go stale). Returns null if the script
 * hasn't been run yet, so callers can fall back gracefully rather than
 * crash the page.
 */
export function loadSampleStoryManifest(): SampleStoryManifest | null {
  if (!existsSync(MANIFEST_PATH)) return null;
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8')) as SampleStoryManifest;
  } catch {
    return null;
  }
}
